name: Validate Pull Requests

on:
  pull_request:

jobs:
  style_check:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install --only=dev
      - name: Check eslint
        run: npm run lint
      - name: Check prettier
        run: npm run prettier-check
    
  build_succeeds:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_website
        with:
          node-version: ${{ vars.NODE_VERSION }}
          artifact-name: website
